### PR TITLE
Delete docs/istio-system-manifests directory

### PR DESCRIPTION
**Pull request by mathieu-benoit**
For the fix of b/242948684 with https://github.com/GoogleCloudPlatform/anthos-config-management-samples/pull/58, we don't need anymore this `istio-system` folder, so removing it.

Let's wait for cl/469357061 to be published before merging this PR.

### CODE REVIEW

**Review by NimJay — APPROVED** [review]
Thank you for pro-actively deleting unused samples.
Approved!

Of course, let's **wait until the CL** for updating the tutorial is submitted before merging this.
The `snippet-bot` check will also pass then.

In the meantime, I have a **question**:
Do you anticipate these samples being useful for a future tutorial?
If so, should we keep them?

**Review by ckim328 — APPROVED** [review]

**Comment by mathieu-benoit** [comment]
Thanks for your review @NimJay! To be honest, it was specific for this tutorial and its dedicated flow, so that's why I want to remove them to avoid any not-used assets and technical debt which may be involved with thtat.

**Comment by mathieu-benoit** [comment]
Let's wait for cl/469357061 to be published before merging that PR.

**Comment by mathieu-benoit** [comment]
cl merged, let's merge this one not complaining anymore (tags removed)

**Pull request merged**
